//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desktop_application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userprofileee
    {
        public string Usersp_Name { get; set; }
        public Nullable<int> Usersp_Age { get; set; }
        public string Usersp_Gender { get; set; }
        public Nullable<long> Usersp_phone_number { get; set; }
        public string Usersp_City { get; set; }
        public string Usersp_Pass { get; set; }
    }
}
